apiVersion: v1
kind: Service
metadata:
  name: hello-world-service
spec:
  type: NodePort
  ports:
    - port: 5000
      targetPort: 5000
      nodePort: 30000  # Você pode escolher uma porta entre 30000 e 32767
  selector:
    app: hello-world
